name: task_manager
description: A new Flutter project.

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  http: ^0.13.3
  connectivity: ^3.0.6
  provider: ^6.0.1
  shared_preferences: ^2.0.7
  flutter_secure_storage: 
  local_auth: ^1.1.7
  permission_handler: ^8.1.4+2
  url_launcher: ^6.0.10
  easy_localization: ^3.0.0
  
  qr_code_scanner: ^0.6.1
  cached_network_image: ^3.2.0
  charts_flutter: ^0.11.0
  cupertino_icons: ^1.0.2
  mask_text_input_formatter: ^2.0.0
  pin_code_fields: ^7.3.0
  
  package_info_plus: ^1.4.0

  # Voice Auth dependencies
  flutter_sound: ^9.1.9
  path_provider: any
  audio_session: ^0.1.6+1
  avatar_glow: ^2.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/flags/
    - assets/translations/ru.json
    - assets/translations/en.json
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-Italic.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-Semibold.ttf
        - asset: fonts/Montserrat-Thin.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-Black.ttf
        - asset: fonts/Montserrat-SemiBold.ttf